### PR TITLE
Use while let pattern

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by 9ary** [comment]
Is it possible to handle error cases with that pattern? (cc @lonami)

**Comment by Lonami** [comment]
What kind of errors would you like to handle, and how? This will stop iteration and exit as soon as there's a `None`, and before we would panic. Is it possible to have a `None` and eventually another `Some`?

**Comment by tnjd** [comment]
"Returns the next event or error from the server.
Returns the next event or error from the server, or returns None in the event of an I/O error. Blocks until either an event or error arrive, or an I/O error occurs."

IMO in the error case we should handle it, print out some message about I/O or other error and quit.

**Comment by 9ary** [comment]
The question is whether it's possible to catch the None and do something with it, though that's more interesting with a Result than an Option so nevermind.

**Comment by 9ary** [comment]
Actually no, we need to differentiate between exiting the loop because of a None as opposed to finishing because the user is done, so this change is wrong.

**Comment by Lonami** [comment]
I mean, currently we panic, so it's also wrong.

**Comment by tnjd** [comment]
I'd be in favour of changing our unwrap to a match, where the error branch exits.

**Comment by 9ary** [comment]
Panicking is more correct, this change allows execution to go down the same path as valid termination.

**Comment by tnjd** [comment]
@pickfire We would welcome a new PR in the direction discussed above. Also, since you seem to be interested in these projects, do you want to join us on Telegram?

**Comment by pickfire** [comment]
@expectocode Where can I find you all in telegram?

**Comment by 9ary** [comment]
The group is public, but the link is intentionally not posted. Search for the name of this organization and you'll find it.

**Pull request closed without merging**
